language: python
sudo: false
python:
  - "3.5"
  - "3.6"

env:
  - TEST_TYPE=unit
  - TEST_TYPE=functional
  - TEST_TYPE=pyopenssl

install:
  - pip install -r development.txt

script:
  - make $TEST_TYPE
